name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environmental variable
      run: echo ::set-env name=IMAGE_NAME::$(echo docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:$(date "+%d%m%y%H%M"))